// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:purr_generator/cats/api/media_player_api.dart';

class _MediaPlayerApiTestHandlerCodec extends StandardMessageCodec {
  const _MediaPlayerApiTestHandlerCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MediaFile) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MediaFile.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class MediaPlayerApiTestHandler {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding => TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> codec = _MediaPlayerApiTestHandlerCodec();

  bool play(MediaFile file);

  void stop();

  void loop(bool looping);

  static void setup(MediaPlayerApiTestHandler? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.purr_generator.MediaPlayerApi.play', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.purr_generator.MediaPlayerApi.play was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MediaFile? arg_file = (args[0] as MediaFile?);
          assert(arg_file != null,
              'Argument for dev.flutter.pigeon.purr_generator.MediaPlayerApi.play was null, expected non-null MediaFile.');
          final bool output = api.play(arg_file!);
          return <Object?>[output];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.purr_generator.MediaPlayerApi.stop', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(channel, (Object? message) async {
          // ignore message
          api.stop();
          return <Object?>[];
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.purr_generator.MediaPlayerApi.loop', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.purr_generator.MediaPlayerApi.loop was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_looping = (args[0] as bool?);
          assert(arg_looping != null,
              'Argument for dev.flutter.pigeon.purr_generator.MediaPlayerApi.loop was null, expected non-null bool.');
          api.loop(arg_looping!);
          return <Object?>[];
        });
      }
    }
  }
}
