// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class MediaPlayerProgressApi {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func onProgress(progress progressArg: Double, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.purr_generator.MediaPlayerProgressApi.onProgress", binaryMessenger: binaryMessenger)
    channel.sendMessage([progressArg] as [Any?]) { _ in
      completion()
    }
  }
  func complete(completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.purr_generator.MediaPlayerProgressApi.complete", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { _ in
      completion()
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MediaPlayerApi {
  func play(fileName: String) throws
  func stop() throws
  func loop(looping: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MediaPlayerApiSetup {
  /// The codec used by MediaPlayerApi.
  /// Sets up an instance of `MediaPlayerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MediaPlayerApi?) {
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.purr_generator.MediaPlayerApi.play", binaryMessenger: binaryMessenger)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fileNameArg = args[0] as! String
        do {
          try api.play(fileName: fileNameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.purr_generator.MediaPlayerApi.stop", binaryMessenger: binaryMessenger)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let loopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.purr_generator.MediaPlayerApi.loop", binaryMessenger: binaryMessenger)
    if let api = api {
      loopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let loopingArg = args[0] as! Bool
        do {
          try api.loop(looping: loopingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loopChannel.setMessageHandler(nil)
    }
  }
}
